version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/css
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/vue
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/react
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /packages/angularjs
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
  - package-ecosystem: npm
    directory: /packages/blazor
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: nuget
    directory: /packages/blazor
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

