import { access, readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = resolve(import.meta.dirname, "..");
const pkg = JSON.parse(await readFile(resolve(root, "package.json"), "utf8"));
const api = JSON.parse(await readFile(resolve(root, "metadata", "public-api.json"), "utf8"));
const compatibility = JSON.parse(await readFile(resolve(root, "metadata", "compatibility.json"), "utf8"));
const css = JSON.parse(await readFile(resolve(root, "..", "css", "metadata", "components.json"), "utf8"));
const runtime = JSON.parse(await readFile(resolve(root, "..", "css", "metadata", "public-api.json"), "utf8"));
const builds = JSON.parse(await readFile(resolve(root, "..", "css", "dist", "gardener.builds.json"), "utf8"));
const componentDocs = await readFile(resolve(root, "docs", "components.md"), "utf8");
const apiDocs = await readFile(resolve(root, "docs", "API.md"), "utf8");
const readme = await readFile(resolve(root, "README.md"), "utf8");
const catalog = await import(pathToFileURL(resolve(root, "dist", "generated", "catalog.js")).href);
const components = await import(pathToFileURL(resolve(root, "dist", "generated", "components.js")).href);
const module = await import(pathToFileURL(resolve(root, "dist", "index.js")).href);
const errors = [];
if (pkg.version !== "2.0.0" || api.version !== pkg.version || api.status !== "stable") errors.push("version/status is not Stable 2.0.0");
if (catalog.componentCatalog.length !== css.components.length || css.components.length !== 506) errors.push("component catalog is incomplete");
if (Object.keys(components.gardenerimComponents).length !== 506) errors.push("generated component registry is incomplete");
if (api.behaviors !== runtime.javascript.behaviors.length || api.behaviors !== 66) errors.push("runtime behavior coverage is incomplete");
if (JSON.stringify(api.packageEntrypoints) !== JSON.stringify(Object.keys(pkg.exports))) errors.push("package exports differ from the public API");
if (JSON.stringify(compatibility.baseline.packageEntrypoints) !== JSON.stringify(Object.keys(pkg.exports))) errors.push("package exports differ from the compatibility baseline");
if (JSON.stringify(api.moduleExports) !== JSON.stringify(Object.keys(module).sort())) errors.push("root module exports differ from the public API");
if (JSON.stringify(compatibility.baseline.moduleExports) !== JSON.stringify(Object.keys(module).sort())) errors.push("root module exports differ from the compatibility baseline");
if (compatibility.baseline.componentNames.length !== 506 || compatibility.baseline.componentExports.length !== 506) errors.push("compatibility baseline is incomplete");
if ((componentDocs.match(/^\| `G[^`]+` \|/gmu) ?? []).length !== 506) errors.push("component documentation is incomplete");
if (JSON.stringify(catalog.componentCatalog.map(({ name }) => name)) !== JSON.stringify(css.components.map(({ name }) => name))) errors.push("React catalog order differs from CSS metadata");
if (JSON.stringify(api.componentExports) !== JSON.stringify(catalog.componentCatalog.map(({ exportName }) => exportName))) errors.push("public API component exports differ from the generated catalog");
if (api.moduleExports.length !== 538 || api.typeExports.length !== 22 || api.packageEntrypoints.length !== 30 || api.hooks.length !== 7 || api.componentProps.length !== 10 || api.themeAxes.length !== 10) errors.push("public API inventory counts are incomplete");
for (const field of ["componentExports", "moduleExports", "typeExports", "packageEntrypoints", "hooks", "componentProps", "componentHandleMembers", "themeAxes"]) if (JSON.stringify(compatibility.baseline[field]) !== JSON.stringify(api[field])) errors.push(`compatibility baseline differs from public API: ${field}`);
for (const marker of [...api.hooks, ...api.componentProps, ...api.componentHandleMembers, ...api.themeAxes, api.provider, "SSR", "StrictMode", "Hydration", "Tauri", "Electron"]) if (!apiDocs.includes(marker)) errors.push(`API documentation is missing ${marker}`);
for (const marker of ["506 个", "66 种", "30 个公共包入口", "React 18.3–19.x", "WCAG A/AA", "release:verify"]) if (!readme.includes(marker)) errors.push(`README is missing ${marker}`);
for (const definition of catalog.componentCatalog) {
  if (!components.gardenerimComponents[definition.exportName]) errors.push(`missing component export: ${definition.exportName}`);
  for (const behavior of definition.behaviors) if (!runtime.javascript.behaviors.includes(behavior)) errors.push(`unknown component behavior: ${definition.name}/${behavior}`);
}
if (builds.componentPacks.length !== 28) errors.push("CSS component pack source is incomplete");
for (const pack of builds.componentPacks) await access(resolve(root, "dist", "component-css", `${pack.name}.css`)).catch(() => errors.push(`missing component CSS proxy: ${pack.name}`));
if (errors.length) throw new Error(`Gardenerim React check failed:\n- ${errors.join("\n- ")}`);
console.log(`Checks passed: ${css.components.length} React components, ${api.behaviors} behaviors, ${Object.keys(pkg.exports).length} package entrypoints.`);
