using Gardener.Blazor.Components;
using Gardener.Blazor.Generated;
using Gardener.Blazor.Models;
using Gardener.Blazor.Services;
using Microsoft.Extensions.DependencyInjection;

var services = new ServiceCollection().AddGardenerBlazor();
if (!services.Any(descriptor => descriptor.ServiceType == typeof(GardenerRuntime))) return 1;
_ = new GButton();
_ = new GardenerField<string>();
if (GardenerCatalog.Components.Count != 506) return 1;
if (GardenerRuntimeCatalog.Behaviors.Count != 66) return 1;
if (GardenerRuntimeCatalog.Events.Count != 75) return 1;
if (GardenerEvents.Guards.Count != 7) return 1;
if (!GardenerRuntimeCatalog.Events.Any(item => item.Name == GardenerEvents.Selectionchange)) return 1;
_ = new GardenerEventArgs(new Dictionary<string, object?> { ["value"] = "verified" }, "selectionchange", false);
var packageVersion = typeof(GButton).Assembly.GetName().Version?.ToString();
if (packageVersion != "1.0.0.0") return 1;
Console.WriteLine("Gardener.Blazor 1.0.0 net11.0 NuGet consumer passed: 506 components, 66 behaviors, 75 events.");
return 0;
